#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../../docs/docstyle.css" />
#+TITLE: Arrays
#+OPTIONS: html-postamble:nil

- [[./ArrayAddk.asm.txt][ArrayAddk]] Traverse an array and add k to
  each element.

- [[./ArrayMax.asm.txt][ArrayMax]] Find the maximum element of an
  array.

- [[./ArraySum.asm.txt][ArraySum]] Calculate the sum of the elements
  of an array.

- [[./DotProduct.asm.txt][DotProduct]] Calculate the dot product of
  two vectors represented as arrays.

- [[./Histogram.asm.txt][Histogram]] Print a histogram that visualises
  the value of each element of an array of numbers.

- [[./StackArrayRobust.asm.txt][StackArrayRobust]] Implement a stack
  using an array.  Check that push doesn't overwrite memory beyond the
  array (stack overflow), and pop isn't applied to an empty stack
  (stack underflow).

- [[./StackArraySimple.asm.txt][StackArraySimple]] Implement a stack
  using an array.  The implementation is simple but unsafe, because it
  doesn't check for stack overflow or underflow.  (See
  StackArrayRobust for a safe version that does check for errors.)
  
- [[./SumCount.asm.txt][SumCount]] Traverse an array and find the sum
  of the positive elements as well as the number of negative elements.
  
