#---------------------------------------------------------------------
# makefile for Sigma16
# John T. O'Donnell.  See README.txt and LICENSE.txt
#---------------------------------------------------------------------

# For version 3
#    make doc
#    make clean
#    make very-clean

# Provide version number in generated html documentation
Sigma16Version = 3.0.4
VersionDate = $(Sigma16Version)

# Requires: ghc, stack, pandoc. Usage:

#  make doc               same as make user-guide
#  make user-guide        create doc/html files from markdown source
#  make compile-windows   build on Windows
#  make clean             delete object code and backup files
#  make very-clean        also delete generated doc/html files
#  make listing           make listing.pdf showing Haskell and pandoc source
#  make archive-tarball   save a .tgz tarball in archive directory
#  make archive-copy      save a full copy in archive directory
#  make list-archive      list the archive directory

# See README.txt for file and directory layout.  The ArchiveLocation
# is relative to the parent directory of Sigma16-i.j.k

ArchiveLocation := ../../archive

#---------------------------------------------------------------------
# Calculate locations and times, don't need to edit these

# Generate filename for archive
PackagePath := $(shell pwd)
PackageName := $(shell basename $(PackagePath))
DateTimeStamp := $(shell date +%Y-%m-%d-at-%H-%M)
BuildDate != date +%d\ %b\ %Y
TarballName := $(PackageName)-on-$(DateTimeStamp).tgz
FullCopyName := $(PackageName)-on-$(DateTimeStamp)


# make show-parameters -- print calculated parameters
.PHONY : show-parameters
show-parameters :
	echo PackagePath = $(PackagePath)
	echo PackageName = $(PackageName)
	echo DateTimeStamp = $(DateTimeStamp)
	echo BuildDate = $(BuildDate)
	echo TarballName = $(TarballName)
	echo FullCopyName = $(FullCopyName)
	echo ArchiveLocation = $(ArchiveLocation)
	echo Sigma16Version = $(Sigma16Version)
	echo VersionDate = $(VersionDate)

.PHONY : listing
listing :
	a2ps -o listing.ps src/haskell/*.hs src/docsrc/index.txt
	ps2pdf listing.ps
	rm -f listing.ps

#---------------------------------------------------------------------
# Generate documentation

# make doc -- generate the html documentation from markdown source
.PHONY : doc
doc :
	mkdir -p doc/html
	cp -r src/docsrc/figures doc/html
	cp src/docsrc/Sigma16doc.css doc/html
	pandoc --standalone \
          --table-of-contents --toc-depth=3 \
          --variable=date:'$(VersionDate)' \
          --variable=css:Sigma16doc.css \
          -o doc/html/index.html \
	  src/docsrc/index.md

#---------------------------------------------------------------------
# Maintaining the directories

# make clean -- remove backup and object files, and temporary
# compilation files.  Leaves executable, documentation, and source in
# place.

.PHONY : clean
clean :
#	rm -rf .cabal-sandbox
#	rm -f cabal.sandbox.config
#	rm -rf dist      # object files for this package
#	runhaskell Setup clean
	rm -f listing.ps listing.pdf
	find . \( -name '*~' -o -name '*.hi' \
	  -o -name '*.bak' \) -delete

# make very-clean -- remove html documentation files generated by
# pandoc, leaving a minimal source directory

.PHONY : very-clean
very-clean :
	make clean
	rm -rf datafiles/doc
#	rm -f Sigma16.exe

# make archive-tarball -- create a tgz file of the entire
# Sigma16-i.j.k directory and place it in the archive directory.  See
# README.txt for directory layout.
.PHONY : archive-tarball
archive-tarball :
	cd .. ; \
	  pwd ; \
	  tar -czf $(TarballName) $(PackageName) ; \
	  mv $(TarballName) $(ArchiveLocation)

# make archive-copy -- create a full copy of the entire Sigma16-i.j.k
# directory and place it in the archive directory.
.PHONY : archive-copy
archive-copy :
	cd ..; \
	  pwd ; \
	  cp -rp $(PackagePath) $(ArchiveLocation)/$(FullCopyName)

# make list-archive -- list contents of the archive directory
.PHONY : list-archive
list-archive :
	ls -lctr ../$(ArchiveLocation)

#----------------------------------------------------------------------
# Currently unsupported, deprecated or out of date...

# Still need to enable launching by clicking application icon...
# New compilation procedure, Oct 21 2015
# using gtk3 and ghc-7.10.2
# cabal isn't working but this seems ok
# I got gtk3 installed successfully for my user account,
# don't need sandbox
# Nov 7 2015: got it working with cabal again
