* Sigma16 source directory

Sigma16 is a computer architecture designed for research and teaching
in computer systems.  This application provides a complete environment
for experimenting with the architecture.  See the user guide in the
docs directory for full documentation.

** Quick start: Running Sigma16 in a web page

You don't need to install anything.  Just visit the [Sigma16 Home
Page](https://jtod.github.io/home/Sigma16/) and click the prominent
link to "Run Sigma16 in your browser".

It is also possible to download the software and run it locally,
without Internet access.  See the Installation section in the User
Guide.

** About Sigma16

The version number is given in the running app on the Welcome page,
the User Guide, and the Options page.

The architecture, implementation, circuits, and examples are
designed and written by [John
O'Donnell](https://jtod.github.io/index.html).

- Copyright (C) 2021 John T. O'Donnell
- License: GNU GPL Version 3 or later
- The full text of the license is given in the source repository in
  Sigma16/LICENSE.txt, as well as at
  [[https://www.gnu.org/licenses][https://www.gnu.org/licenses]].

Sigma16 is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

Sigma16 is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with Sigma16.  If not, see
[[https://www.gnu.org/licenses][https://www.gnu.org/licenses]].
