* Sigma16 source directory

Sigma16 is a computer architecture designed for research and teaching
in computer systems.  This application provides a complete environment
for experimenting with the architecture.

** Quick start: Running Sigma16 in a web page

You don't need to install anything.  Just visit the [Sigma16 Home
Page](https://jtod.github.io/home/Sigma16/) and click the prominent
link to "Run Sigma16 in your browser".
  
** Internet links

The [Sigma16 Home Page
(https://jtod.github.io/home/Sigma16/)](https://jtod.github.io/home/Sigma16/)
contains a link to "Run Sigma16 in your browser", as well as links to
documentation, past releases, and the source repository [source
repository
(https://github.com/jtod/Sigma16/)](https://github.com/jtod/Sigma16/).
It's best to bookmark the home page, which always points to the latest
version.

** Download and run locally

To run the IDE (the graphical user interface) there is no need to
download or install the software: you can just *Click to run Sigma16
in your browser* in the [Sigma16 Home
Page](https://jtod.github.io/home/Sigma16/).

The Home Page also provides a link to download the app.  If you copy
the Sigma16 source directory onto your computer, the following links
will run it locally without any additional software installation and
without requiring further access to the Internet.  However, these
links will not work if you're reading this page on the source
repository on GitHub via the Internet.

- [Launch from files in this directory](./app/Sigma16.html) If you
  have copied this directory onto a local machine, this link will run
  it.  The advantage is that you won't need access to the Internet.
  However, browsers have restricted access to your file system, to
  ensure security.  One consequence of this is that the *Select
  example* button in the *Examples* page won't do anything.  But you
  can select the text of the example with your mouse, right-click and
  Copy, then Paste it into the Editor page.  It's also possible to
  install Sigma16 as an app on your computer; that gets rid of the
  restrictions on file access.  See the Installation section in the
  User Guide.

- [Up to the top directory](./) Show the listing of files in the
  directory containing this version.

** Installing the command line tools

In addition to the basic web page version of Sigma16, there is a
collection of separate programs that can be run in a shwll from the
command line.  *(These are under development and will be released in
late 2020; please come back later.)* These programs include a
standalone version of the IDE, fast emulator, circuit simulator, and
more.  These tools provide additional functionality, faster execution,
and the ability to work without access to the Internet.

** About the software

The Sigma16 app (the integrated development environment -- i.e. the
GUI) is implemented in JavaScript, html 5, and css.  The digital
circuit is implemented in Hydra, which requires Haskell.  Additional
software tools, including a high speed emulator, are in progress and
expected to be available in late 2020.

*** Author

The architecture is designed by, and the software tools are written
by, [John O'Donnell](https://jtod.github.io/index.html).

- Email: john.t.odonnell9@gmail.com
- Web: https://jtod.github.io/index.html


*** Copyright and license

- Copyright (C) 2019, 2020 John T. O'Donnell
- License: GNU GPL Version 3 or later
- See Sigma16/LICENSE.txt

Sigma16 is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

Sigma16 is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with Sigma16.  If not, see <https://www.gnu.org/licenses/>.

# Local Variables:
# org-html-preamble: "<h1>Sigma16</h1>
#   Version 3.1.4 (October 2020).
#   Copyright (c) 2020 John T. O'Donnell.
#   For the latest version, see
#   <a href=\"https://jtod.github.io/home/Sigma16/\">
#     https://jtod.github.io/home/Sigma16/</a>"
# End:
