#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../docstyle.css" />
#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+BEGIN_EXPORT html
<h1>Sigma16</h1>
#+END_EXPORT

#+INCLUDE: "../../VERSION.txt" export html

** Overview

Sigma16 is a computer architecture designed for research and teaching
in computer systems.  This application provides a complete environment
for experimenting with the architecture, including an editor,
assembler, linker, emulator, and an integrated development
environment.  There is a digital circuit that implements the
architecture, which is specified using the Hydra functional hardware
description language.  Hydra can simulate the circuit, and machine
language programs can run on both the emulator and the circuit.

** Getting started

The User Guide begins with a set of tutorials that introduce the
system.  The best place to start is with the *Hello, World!* tutorial.
After working through the tutorials, see the rest of the User Guide
for detailed documentation.

#+BEGIN_EXPORT html
The User Guide appears in the right side of the window.  You can
increase or decrease its size by clicking the arrow buttons at the
right side of the top button box, and you can also <a
href="../../docs/UserGuide/Sigma16UserGuide.html" target="_blank">open
the user guide in a new window</a>.
#+END_EXPORT

** Updates and further information

#+BEGIN_EXPORT html
The <a href="https://jtod.github.io/home/Sigma16/"
target="_blank">Sigma16 Home Page</a> contains a link to run the
latest version as well as up-to-date information on the system.  It's
best to bookmark the home page, not this specific release.  If you
always launch the app by clicking the link in the home page, you'll
always be running the most recent release.
#+END_EXPORT

#+BEGIN_EXPORT html
The source code is available on the <a
href="https://github.com/jtod/Sigma16/" target="_blank">source
repository</a>.
#+END_EXPORT

** License

License: GNU GPL Version 3 or later.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

#+BEGIN_EXPORT html
You should have received a copy of the GNU General Public License
along with this program.  If not, see <a
href="https://www.gnu.org/licenses/"
target="_blank">https://www.gnu.org/licenses/</a>
#+END_EXPORT
