#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../docs/docstyle.css" />
#+TITLE: Sigma16 example programs

- [[./Core/index.html][Core]] Simple programs that use only the small
  core subset of the architecture.  The core instructions are add,
  sub, mul, div, trap, lea, load, store, jump, jal, jumpXX.

- [[./Standard/index.html][Standard]] Programs that use the standard
  Sigma16 instruction set.  In addition to the Core instructions,
  there are instructions for logic, bit manipulation, Input/Output,
  flexible implementation of functions and procedures, and more.
  2These programs illustrate intermediate programming techniques, such
  as records, pointers, bit fields, linked data structures, recursion,
  and case dispatch.

- [[./S16/index.org][S16]] Programs that use the complete Sigma16
  instruction set architecture.  This is the Standard architecture as
  well as instructions that manipulate the system control registers
  and provide interrupts, segmentation, processes, and mutual
  exclusion.  The full architecture supports simple operating system
  kernels. 

- [[./S32/index.org][S32]] Sigma32 is an extension of Sigma16 to allow
  32 bit full words.  The architecture is backwards compatible with
  Sigma16, and it allows a larger address space as well as operations
  that require full words.

- [[./Testing/index.html][Testing]] Programs for testing the system.
