* Assembler

The assembler translates a /source program/ from assembly language to
an /object program/ in machine language.

First put an assembly language program into the editor (loading a file
puts it into the editor automatically, or you can click /editor/ and
enter or change the program manually.  Then click the /Assembler/ tab
and click /assemble/.

- *assemble* translates the source code from assembly language to
  machine language.  The source code is obtained from the editor page.
  When you click assemble, the listing is displayed automatically.
- *show source* displays the assembly language source code
- *show object* displays the object code produced by the assembler.
  This contains =data= statements giving the machine language code, as
  well as other statements that give further information required by
  the linker (including =org=, =relocat=, =import=)
- *show listing* displays the assembly listing.  Each line of the
  listing contains a line of source code, as well as the machine
  language object code and the address where the object code will be
  placed.
- *show metadata* displays some additional information produced by the
  assembler.  The metadata is used by the emulator to help show how
  the program is executed.  For example, the emulator highlights the
  line of source code corresponding to an instruction being executed;
  the metadata helps the emulator to figure out which line of source
  corresponds to an instruction address.  The metadata is not part of
  the program, and does not affect the execution of the program.
  Normally you won't need to look at the metadata.
