* Processor

The processor page displays the state of the machine: the registers
and memory.  The top left section shows the control registers, the
register file, and the memory.  There are two views into the memory,
which is useful for decoding linked data structures.  The top right
contains a small text box for typeing input, and a log of all the
input/output.  The bottom section shows the assembly language code.

- Help (key h) Show or hide the help panel
- Boot (key b) If the assembler or linker has produced an executable
  machine language program, load that into the memory and set the
  Processor Status to Ready.  If there isn't an executable program,
  boot does nothing.
- Step (key s) Execute one instruction.
- Run (key r) Run the program until a stopping condition (halt, pause,
  breakpoint)
- Pause (key p) Stop execution of the program and display the
  registers and memory; leave the machine in the Ready state.
  Execution can be resumed by either Step or Run.

