** Typesetting

*** Links

- Link to a section: see [[*Core architecture tutorials]]
- Link to a subsection: see [[** A strange program]]
- Link to a destination in double angle brackets: the execute
  instruction is discussed in [[strange execute anchor]]

*** Code listings

The right way to do it.  The BEGIN_example tells org to use a verbatim
environment for latex, and a pre environment for html.  It doesn't put
in a p environment, which introduces an unwanted blank line at the top
of the code for html.  The BEGIN_CodeListing introduces a div in html
and an environment in latex; these allow for formatting to be
introduced.

#+BEGIN_CodeListing
#+BEGIN_example
      load   R1,a[R0]      ; R1 := a
      load   R2,b[R0]      ; R2 := b
loop  add    R3,R1,R2      ; R3 := a+b
      load   R4,c[R0]      ; R4 := c
      add    R5,R3,R4      ; R5 := (a+b) + c
      store  R5,x[R0]      ; x := a+b+c
#+END_example
#+END_CodeListing

This is some code in BEGIN_EXAMPLE, without the CodeListing:

#+BEGIN_EXAMPLE
      load   R1,a[R0]      ; R1 := a
      load   R2,b[R0]      ; R2 := b
loop  add    R3,R1,R2      ; R3 := a+b
      load   R4,c[R0]      ; R4 := c
      add    R5,R3,R4      ; R5 := (a+b) + c
      store  R5,x[R0]      ; x := a+b+c
#+END_EXAMPLE

This is some code in CodeListing, without the example environment:

#+BEGIN_CodeListing
      load   R1,a[R0]      ; R1 := a
      load   R2,b[R0]      ; R2 := b
loop  add    R3,R1,R2      ; R3 := a+b
      load   R4,c[R0]      ; R4 := c
      add    R5,R3,R4      ; R5 := (a+b) + c
      store  R5,x[R0]      ; x := a+b+c
#+END_CodeListing
