#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../../docs/docstyle.css" />
#+TITLE: Input/Output
#+OPTIONS: html-postamble:nil

These programs illustrate how to do Input/Output.  This is done by
using a trap instruction to request the I/O.  The trap instruction is
RRR, and it takes three register operands.  The first register
(specified by the d field) contains a code indicating what operation
is being requested (0=halt, 1=read, 2=write, and so on).  The second
register (specified by the a field) gives the address of a buffer (an
array of characters to be read or written, and the third register
(specified by the b field) gives the number of characters to read or
write.

- [[./Write.asm.txt][Write]] Demonstrate how to output a character
  string.

- [[./Read.asm.txt][Read]] Demonstrate how to read some input from the
  user.

- [[./ReadWrite.asm.txt][ReadWrite]] Read some input from the user and
  then write it back out.

- [[./WriteChunks.asm.txt][WriteChunks]] Write several short strings
  on the same line, and write several lines.
